#include "fmt/core.h"
#include "postprocess.h"
#include "serialize.h"
#include "shared.h"
#include <array>
#include <cstdio>
#include <memory>
#include <stdexcept>
#include <string>
#include <unistd.h>

static int global_argc;
static char **global_argv;

int get_number_of_groups(H5::H5File &file);

void set_program_args(int argc, char **argv)
{
    global_argc = argc;
    global_argv = argv;
}

std::string get_program_argv()
{
    return fmt::format("{}", fmt::join(std::vector<std::string_view>(global_argv, global_argv + global_argc), " "));
}

char **get_program_raw_argv()
{
    return global_argv;
}

int get_number_of_solutions(const std::string &path)
{
    TWIST::FileType file_type;
    H5::H5File h5_file(path, H5F_ACC_RDONLY);
    int ngroups = get_number_of_groups(h5_file);

    if (!h5_file.exists("meta_data")) {
        throw std::runtime_error(fmt::format("meta_data is not present. {} was likely not generated by twist continuation or was corrupted.", path));
    }

    H5::Group group{ h5_file.openGroup("meta_data") };
    deserialize(group, "file_type", file_type);

    switch (file_type) {
    case TWIST::FileType::continuation:
        ngroups -= 2;
        break;
    case TWIST::FileType::spectrum:
        ngroups -= 1;
        break;
    case TWIST::FileType::bifurcation_points:
        ngroups -= 2;
        break;
    case TWIST::FileType::preprocess:
        ngroups = 1;
        break;
    default:
        break;
    }

    return ngroups;
}

herr_t op_func(hid_t, const char *, const H5L_info_t *, void *op_data)
{
    int *idata = (int *)op_data;
    // puts(name);
    idata[0] += 1;
    return 0;
}

int get_number_of_groups(H5::H5File &file)
{
    int group_count = 0;
    H5Literate(file.getId(), H5_INDEX_NAME, H5_ITER_INC, NULL, op_func, &group_count);
    return group_count;
}

int get_number_of_solutions(H5::H5File &h5_file)
{
    TWIST::FileType file_type;
    int ngroups = get_number_of_groups(h5_file);

    if (!h5_file.exists("meta_data")) {
        throw std::runtime_error(fmt::format("meta_data is not present. {} was likely not generated by twist continuation or was corrupted.", h5_file.getFileName()));
    }

    H5::Group group{ h5_file.openGroup("meta_data") };
    deserialize(group, "file_type", file_type);

    switch (file_type) {
    case TWIST::FileType::continuation:
        ngroups -= 2;
        break;
    case TWIST::FileType::spectrum:
        ngroups -= 1;
        break;
    case TWIST::FileType::bifurcation_points:
        ngroups -= 2;
        break;
    case TWIST::FileType::preprocess:
        ngroups = 1;
        break;
    default:
        break;
    }

    return ngroups;
}