#include "cli/cli_info.h"
#include "serialize.h"
#include "tools/helpers.h"
#include <numeric>

int InfoArgs::run()
{
    this->validate(true);

    verify_hdf5_file(file);

    std::vector<int> indices;
    H5::H5File h5_file(file, H5F_ACC_RDONLY);
    TWIST::FileType file_type;
    H5::Group group = h5_file.openGroup("meta_data");
    deserialize(group, "file_type", file_type);
    size_t ngroups = get_number_of_solutions(h5_file);

    if (which_indices.size() == 0) {
        indices.resize(ngroups);
        std::iota(indices.begin(), indices.end(), 0);
    }
    else {
        indices = parse_indices_and_slices(which_indices, ngroups);
    }
    if (get_length) {
        if (file_type == TWIST::FileType::continuation) {
            fmt::println(COLOR_MAGENTA "There are {} solutions in '{}'" COLOR_RESET, ngroups, file);
        }
        else if (file_type == TWIST::FileType::spectrum) {
            fmt::println(COLOR_MAGENTA "There are {} spectra in '{}'" COLOR_RESET, ngroups, file);
        }
        else if (file_type == TWIST::FileType::bifurcation_points) {
            fmt::println(COLOR_MAGENTA "There are {} bifurcation points in '{}'" COLOR_RESET, ngroups, file);
        }
    }
    if (spectrum_info && (file_type == TWIST::FileType::continuation)) {
        print_spectrum_info(h5_file, indices, ngroups, stype_filter);
    }
    if (show_params && (file_type == TWIST::FileType::continuation || file_type == TWIST::FileType::bifurcation_points)) {
        int parnum;
        std::vector<int> pindices;
        // get path to spec file
        char *cmdline = nullptr;
        deserialize(group, "cmdline", cmdline);
        std::string cmdline_s{ cmdline };
        std::string spec_file{ split(cmdline_s, " ")[2] };
        fmt::println("spec file: {}", spec_file);

        // extract parameter names
        simdjson::dom::parser parser;
        simdjson::dom::element doc = parser.load(spec_file);
        std::string name{ doc["name"].get_c_str() };
        auto params = entry_to_list<std::string>("params", doc, false);

        if (which_params.empty()) {
            which_params = { "c" };
            for (const auto &pname : params) {
                which_params.emplace_back(pname);
            }
            which_params.emplace_back("sps");
#if TEST_WAVE_NUMBER_PARAM
            which_params.emplace_back("wave_number");
#endif
        }

        // get indices of parameters
        for (const auto &parameter : which_params) {
            auto loc = std::find(params.begin(), params.end(), parameter);
            if ((parameter == "sps") || (parameter == "spatial_period_scale")) {
                parnum = params.size() + 1;
            }
            else if (parameter == "c") {
                parnum = 0;
            }
#if TEST_WAVE_NUMBER_PARAM
            else if (parameter == "wave_number") {
                parnum = params.size() + 2;
            }
#endif
            else if (loc == params.end()) {
                fmt::println("'{}' is not a valid parameter name", parameter);
                exit(1);
            }
            else {
                parnum = 1 + (loc - params.begin());
            }
            pindices.emplace_back(parnum);
        }
        print_parameter_values(h5_file, indices, ngroups, which_params, pindices, stype_filter);
    }

    if (print_meta_data) {
        // TWIST::FileType::continuation, TWIST::FileType::preprocess, TWIST::FileType::bifurcation_points, TWIST::FileType::spectrum
        char *cmdline = nullptr;
        char *directory = nullptr;
        deserialize(group, "cmdline", cmdline);
        deserialize(group, "directory", directory);
        if (file_type == TWIST::FileType::continuation) {
            fmt::println("file type    : continuation");
            fmt::println("ran in       : {}", directory);
            fmt::println("command line : {}", cmdline);
        }
        else if (file_type == TWIST::FileType::spectrum) {
            fmt::println("file type    : spectrum");
            fmt::println("command line : {}", cmdline);
        }
        else if (file_type == TWIST::FileType::bifurcation_points) {
            fmt::println("file type    : bifurcation points");
            fmt::println("command line : {}", cmdline);
        }
        else if (file_type == TWIST::FileType::preprocess) {
            fmt::println("file type    : preprocess");
            fmt::println("ran in       : {}", directory);
            fmt::println("command line : {}", cmdline);
        }
        free(cmdline);
        free(directory);
    }
    return 0;
}


void InfoArgs::welcome()
{
    fmt::println("Print info about a file generated by TWIST");
}